config/routes.rb
Rails.application.routes.draw do
  resources :orders, only: %i[index create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
  validates_presence_of :email, :first_name, :last_name, :amount
  validates :email, format: { with: /\A[\w.]+@\w+\.\w+\z/ }
  validates :first_name, format: { with: /\A\w{2,}\z/,
                                   message: 'Only one word containing more than two letters' }
  validates :last_name, format: { with: /\A\w{2,}\z/,
                                  message: 'Only one word containing more than two letters' }
  validates :amount, numericality: { only_integer: true }

  scope :email, -> (email) { where("email like ?", "#{email}%") }
  scope :last_name, -> (last_name) { where("last_name like ?", "#{last_name}%") }

  def self.filter(filter)
    orders = Order.email(filter[:email])
    orders.last_name(filter[:last_name])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
    if params[:filter]
      @orders = Order.filter(params[:filter])
    else
      @orders = Order.all
    end
  end

  def create
    order = Order.new(order_params)
    if order.save
      render json: { notice: 'Created' }
    else
      render json: { errors: order.errors }, status: 400
    end
  end

  private

  def order_params
    params.require(:order).permit(:email, :first_name, :last_name, :amount)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SalesDashboard</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class='container'>
      <%= yield %>
    </div>
  </body>
</html>

app/views/orders/index.html.erb
<p>
  <%= form_tag orders_path, method: :get do |f| %>
    <%= text_field_tag 'filter[email]', nil, placeholder: 'Filter by email' %> <br>
    <%= text_field_tag 'filter[last_name]', nil, placeholder: 'Filter by last name' %> <br>
    <%= submit_tag 'Filter' %>
  <% end %>
</p>

<table id='ordersTable' class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Email</th>
      <th>Amount</th>
    </tr>
  </thead>
  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.first_name %></td>
        <td><%= order.last_name %></td>
        <td><%= order.email %></td>
        <td><%= order.amount %></td>
      </tr>
    <% end %>
  </tbody>
</table>